# Generated by Django 4.2.1 on 2023-08-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='Course Name', max_length=50)),
                ('professor', models.CharField(default='Professor Name', max_length=50)),
                ('building', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('registered', models.IntegerField()),
                ('available', models.IntegerField(default=30)),
            ],
        ),
    ]
