# Generated by Django 4.2.1 on 2023-08-30 16:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0007_alter_course_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(null=True, related_name='registered', to=settings.AUTH_USER_MODEL),
        ),
    ]
